[2024-07-22T16:56:57.665+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T16:56:57.879+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [queued]>
[2024-07-22T16:56:57.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [queued]>
[2024-07-22T16:56:57.887+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T16:56:57.897+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): sensor_congestion> on 2024-07-02 06:00:00+00:00
[2024-07-22T16:56:57.906+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=895) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T16:56:57.907+0000] {standard_task_runner.py:64} INFO - Started process 900 to run task
[2024-07-22T16:56:57.908+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'sensor_congestion', 'scheduled__2024-07-02T06:00:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpwdpgg5oo']
[2024-07-22T16:56:57.909+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask sensor_congestion
[2024-07-22T16:56:57.947+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T16:56:58.024+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='sensor_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T06:00:00+00:00'
[2024-07-22T16:56:58.025+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T16:56:58.033+0000] {python.py:75} INFO - Poking callable: <function check_data_in_table at 0x7286306f62a0>
[2024-07-22T16:56:58.037+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T16:56:58.037+0000] {extract.py:128} INFO - where date is 2024-07-01
[2024-07-22T16:56:58.038+0000] {extract.py:99} INFO - get data to date 27 and year 2024
[2024-07-22T16:56:58.043+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:14:43.112+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-07-22T17:14:43.114+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:14:43.115+0000] {process_utils.py:132} INFO - Sending 15 to group 900. PIDs of all processes in the group: [900]
[2024-07-22T17:14:43.115+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 900
[2024-07-22T17:14:43.116+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-22T17:14:43.116+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:14:43.128+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-22T17:14:43.133+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=motower_daily_prod, task_id=sensor_congestion, run_id=scheduled__2024-07-02T06:00:00+00:00, execution_date=20240702T060000, start_date=20240722T165657, end_date=20240722T171443
[2024-07-22T17:14:43.208+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=900, status='terminated', exitcode=2, started='16:56:56') (900) terminated with exit code 2
[2024-07-22T17:16:11.123+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:16:11.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [queued]>
[2024-07-22T17:16:11.335+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [queued]>
[2024-07-22T17:16:11.336+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:16:11.348+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): sensor_congestion> on 2024-07-02 06:00:00+00:00
[2024-07-22T17:16:11.356+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1283) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:16:11.358+0000] {standard_task_runner.py:64} INFO - Started process 1289 to run task
[2024-07-22T17:16:11.359+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'sensor_congestion', 'scheduled__2024-07-02T06:00:00+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmpqmt_ewot']
[2024-07-22T17:16:11.361+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask sensor_congestion
[2024-07-22T17:16:11.397+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:16:11.470+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='sensor_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T06:00:00+00:00'
[2024-07-22T17:16:11.471+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:16:11.480+0000] {python.py:75} INFO - Poking callable: <function check_data_in_table at 0x7286306f93a0>
[2024-07-22T17:16:11.483+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:16:11.483+0000] {extract.py:128} INFO - where date is 2024-07-01
[2024-07-22T17:16:11.483+0000] {extract.py:99} INFO - get data to date 27 and year 2024
[2024-07-22T17:16:11.487+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-22T17:42:51.337+0000] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-07-22T17:42:51.338+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-22T17:42:51.340+0000] {process_utils.py:132} INFO - Sending 15 to group 1289. PIDs of all processes in the group: [1289]
[2024-07-22T17:42:51.340+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1289
[2024-07-22T17:42:51.340+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-22T17:42:51.341+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-22T17:42:51.349+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-22T17:42:51.352+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=motower_daily_prod, task_id=sensor_congestion, run_id=scheduled__2024-07-02T06:00:00+00:00, execution_date=20240702T060000, start_date=20240722T171611, end_date=20240722T174251
[2024-07-22T17:42:51.392+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1289, status='terminated', exitcode=2, started='17:16:10') (1289) terminated with exit code 2
[2024-07-22T17:43:32.746+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-22T17:43:32.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [queued]>
[2024-07-22T17:43:32.969+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [queued]>
[2024-07-22T17:43:32.970+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-22T17:43:32.981+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonSensor): sensor_congestion> on 2024-07-02 06:00:00+00:00
[2024-07-22T17:43:32.991+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=1845) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-22T17:43:32.992+0000] {standard_task_runner.py:64} INFO - Started process 1853 to run task
[2024-07-22T17:43:32.992+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'motower_daily_prod', 'sensor_congestion', 'scheduled__2024-07-02T06:00:00+00:00', '--job-id', '186', '--raw', '--subdir', 'DAGS_FOLDER/gps/custom_dags/motower_daily.py', '--cfg-path', '/tmp/tmplsa4sc4q']
[2024-07-22T17:43:32.994+0000] {standard_task_runner.py:91} INFO - Job 186: Subtask sensor_congestion
[2024-07-22T17:43:33.036+0000] {task_command.py:426} INFO - Running <TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [running]> on host 5e959f2258db
[2024-07-22T17:43:33.115+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='richmond.kongo@orange.com,assane.diop@orange.com,cyrille1.danho@orange.com,mohamed2.sylla@orange.com,amadou.diomande@orange.com,Jonas.kouame@orange.com,armand.kablan@orange.com,anicet.azombade@orange.com,etienne.kouadio@orange.com,bertine.kouakou@orange.com,florentine.kouakou@orange.com,ange.phaceli@orange.com,soulegame.soro@orange.com,innocent.yengo@orange.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='motower_daily_prod' AIRFLOW_CTX_TASK_ID='sensor_congestion' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T06:00:00+00:00'
[2024-07-22T17:43:33.116+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-22T17:43:33.126+0000] {python.py:75} INFO - Poking callable: <function check_data_in_table at 0x72864fe4ad40>
[2024-07-22T17:43:33.130+0000] {extract.py:127} INFO - Getting data of the table ks_hebdo_tdb_radio_drsi 
[2024-07-22T17:43:33.130+0000] {extract.py:128} INFO - where date is 2024-07-01
[2024-07-22T17:43:33.130+0000] {extract.py:99} INFO - get data to date 27 and year 2024
[2024-07-22T17:43:33.135+0000] {warnings.py:112} WARNING - /opt/***/dags/gps/common/extract.py:100: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ = pd.read_sql_query(sql_query, conn, params=params)

[2024-07-23T09:42:55.126+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-23T09:42:55.408+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [running]>, dependency 'Task Instance State' FAILED: Task is in the 'running' state.
[2024-07-23T09:42:55.408+0000] {taskinstance.py:2066} INFO - Dependencies not met for <TaskInstance: motower_daily_prod.sensor_congestion scheduled__2024-07-02T06:00:00+00:00 [running]>, dependency 'Task Instance Not Running' FAILED: Task is in the running state
[2024-07-23T09:42:55.410+0000] {local_task_job_runner.py:163} INFO - Task is not able to be run
